row=400;  col=480;
file_raw = 'tif.raw';
fin=fopen(file_raw,'r');
I=fread(fin,row*col,'uint8=>uint8'); 
Z=reshape(I,row,col);
Z=Z';
%Z = dither(Z);
fclose(fin);
figure('Name',file_raw,'NumberTitle','off');
subplot(1,2,1);
imshow(Z);
title(file_raw);

file_FloydSteinbergDithering = 'FloydSteinbergDithering.raw';
fin_FloydSteinbergDithering=fopen(file_FloydSteinbergDithering,'r');
I_FloydSteinbergDithering=fread(fin_FloydSteinbergDithering,row*col,'uint8=>uint8'); 
Z_FloydSteinbergDithering=reshape(I_FloydSteinbergDithering,row,col);
Z_FloydSteinbergDithering=Z_FloydSteinbergDithering';
fclose(fin_FloydSteinbergDithering);
subplot(1,2,2);
imshow(Z_FloydSteinbergDithering);
title(file_FloydSteinbergDithering);
